set -g default-shell /opt/homebrew/bin/fish

# Enable 256-color and true-color (24-bit) support in tmux
set -g default-terminal "screen-256color" # Set terminal type for 256-color support
set -ga terminal-overrides ",*256col*:Tc" # Override to enable true-color for compatible terminals

# General
set -g set-clipboard on # 使用系统剪贴板
set -g escape-time 0 # 关闭 ESC 延迟
set -g history-limit 200000
set -g mouse on
set -g allow-passthrough on # 让 tmux 不再拦截某些键/转义序列，而是原封不动地转发给 pane 里的程序

set-window-option -g mode-keys vi

# Use prefix + hjkl to move between panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
